[package]
name = "a90"
description = "RC4-128-HMAC file encryption with executable-local key.key"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
keyfile-core.workspace = true
zeroize.workspace = true
cipher.workspace = true
rc4.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
