[package]
name = "a10"
description = "Ascon-AEAD128 file encryption with executable-local key.key"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
keyfile-core.workspace = true
zeroize.workspace = true
aead.workspace = true
ascon-aead.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
