[package]
name = "a14"
description = "XChaCha12Poly1305 file encryption with executable-local key.key"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
keyfile-core.workspace = true
zeroize.workspace = true
aead.workspace = true
chacha20poly1305.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
